### ISSUE TITLE
How to empty the dictionary quickly

### ISSUE THREAD

**Issue by FrankDataAnalystPython** [mammothb/symspellpy#125]
Dear Sir:
I am just wondering is there a way to empty the .words dict quickly in an inexpensive way after loading dictionary.

I am facing a case where I need to constantly update the dictionary of the symspell, but it is very slow for each initialization

Regards

**Comment by FrankDataAnalystPython** [comment]
Dear Sir:
 I am also wondering, is there a way to just focus on a subset of the symspell.words for calculating the distance? Many Thanks

Regards

**Comment by mammothb** [comment]
> I am just wondering is there a way to empty the .words dict quickly in an inexpensive way after loading dictionary.
> 
> I am facing a case where I need to constantly update the dictionary of the symspell, but it is very slow for each initialization

The words and other related data are found within these [member variables](https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L97-L101) and are implemented as dictionary. So I think you can probably just use the Python built-in dictionary `clear()` function.

> I am also wondering, is there a way to just focus on a subset of the symspell.words for calculating the distance?

You'll have to write your custom functions/methods for this. You can perhaps try to load a subset of the dictionary words before running lookup methods.

To make switching of different dictionary "subset" quicker, I think you can save the `words` and related member variables as pickles and then just load them instead of having to parse them again.

**Comment by FrankDataAnalystPython** [comment]
Many Thanks!!!
