### ISSUE TITLE
what exactly is max_edit_distance_dictionary

### ISSUE THREAD

**Issue by bastia1989** [mammothb/symspellpy#48]
What exactly does `max_edit_distance_dictionary` do, and why it should be larger than `max_edit_distance`.

Thanks.

**Comment by mammothb** [comment]
It determines the content in `_deletes` dictionary. The keys are the edit candidates generated by only deletes which are within an edit distance of 1 to `max_edit_distance_dictionary` of the original words. The dictionary values are lists of suggested correction words.

For example, with a `max_edit_distance_dictionary = 1`, `_deletes` contains 
```
'{te': ['the'], 'he': ['the'], 'the': ['the'], 'th': ['the']}
```
and when `max_edit_distance_dictionary = 2`, `_deletes` contains
```
'h': ['the'], 'e': ['the'], 'he': ['the'], 'th': ['the'], 't': ['the'], 'te': ['the'],
'the': ['the']}
```
"h", "e" and "t" were not previously included since they can only be obtained by making 2 deletes (edits) from the original word "the".

`prefix_length` also plays a part in generating `_deletes` since it limits the "original word" from which we make deletes. For example, when `prefix_length = 7`, "unhpi" can be mapped to "unhappiness" since it's 2 deletes from "unhappi".

So we enforce `max_edit_distance <= max_edit_distance_dictionary` since `_deletes` will contain any mapping with an edit distance greater then `max_edit_distance_dictionary`. There was also a mistake in [`_edits_prefix()`](https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L905),
```
if len(key) > self._max_dictionary_edit_distance:
```
should have been
```
if len(key) > self._prefix_length:
```
I'm sorry if that caused this confusion.

**Comment by bastia1989** [comment]
Thanks, it is very clear now. So [_edits_prefix()](https://github.com/mammothb/symspellpy/blob/cdc6b172c6a2262a387476ab656dd31fc9e32d08/symspellpy/symspellpy.py#L905) will be fixed in the later version, right?

**Comment by mammothb** [comment]
The changes has been pushed to the `dev` branch, I'll merge it to `master` later. Interestingly, it does not seem to affect the accuracy of the program since having a stop index larger then the string length is handled gracefully in python. For example
```
s = "abc"
print(s[: 10])
```
gives
```
abc
```
which is what `_edits_prefix()` wanted.
