### ISSUE TITLE
lookup_compound result not consistent with the word frequency

### ISSUE THREAD

**Issue by bastia1989** [mammothb/symspellpy#49]
Using self-defined dictionary, The code is:
```
from symspellpy.editdistance import EditDistance, DistanceAlgorithm
from symspellpy.symspellpy import SymSpell, Verbosity 

max_edit_distance_dictionary = 2
prefix_length = 7
max_edit_distance_lookup = 1
suggestion_verbosity = Verbosity.TOP
# create object
sym_spell = SymSpell(max_edit_distance_dictionary, prefix_length)
sym_spell.load_dictionary('dictionary.txt', term_index=0, count_index=1)
```
By comparing the distance of the original string and 2 correction candidates as:
```
ed = EditDistance(DistanceAlgorithm.DAMERUAUOSA)
ed.compare('andbanana', 'an banana', max_distance=2)
ed.compare('andbanana', 'and banana', max_distance=2)
```
the distances are both 1

However, by using
`sym_spell.lookup_compound(input_term, max_edit_distance_lookup, transfer_casing=True)`
the result is
`an banana`
However, in the dictionary the frequency of `and` is much higher than `an`, and the frequency of them are both lower than `banana`. How `an banana` is ranked higher than `and banana`?

Thanks.

**Comment by mammothb** [comment]
Currently, we are exiting early when the edit distance of the suggested correction is 1 compared to the input string ([line 680](https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L680)). Usually this means that we only had to break up the input string by inserting a space, but in this particular case it was by removing "d" from "and".

Even if we decided to not exit early, `an banana` is still returned since the frequency of the suggested correction is the chosen as the minimum frequency among the individual suggestion terms ([line 674](https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L674)). This is consistent with the logic in the [original code](https://github.com/wolfgarbe/SymSpell/blob/master/SymSpell/SymSpell.cs#L882).

You could try `word_segmentation()` if you want to break up the input string into individual words.

**Comment by bastia1989** [comment]
> Currently, we are exiting early when the edit distance of the suggested correction is 1 compared to the input string ([line 680](https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L680)). Usually this means that we only had to break up the input string by inserting a space, but in this particular case it was by removing "d" from "and".
> 
> Even if we decided to not exit early, `an banana` is still returned since the frequency of the suggested correction is the chosen as the minimum frequency among the individual suggestion terms ([line 674](https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L674)). This is consistent with the logic in the [original code](https://github.com/wolfgarbe/SymSpell/blob/master/SymSpell/SymSpell.cs#L882).
> 
> You could try `word_segmentation()` if you want to break up the input string into individual words.

Thanks for the reply. So the logic here is that the less frequent candidate (among those of same edit distance) is returned. This is a little bit counter intuitive.

**Comment by mammothb** [comment]
We'll use these frequencies for the dictionary `an: 10`, `and: 100`, and `banana: 200`. So the correction distance and count will be `an banana, 1, 10` and `and banana, 1, 100`.

Without the early exit, `and banana, 1, 100` is returned (by manually commenting it out in the code). The `sort()` works as intended, comparing by edit distance first and preferring higher frequency when a tie occurs ([line 963](https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L963)).

However, **with** early exit, `an banana, 1, 10` is returned. Since when input string is split ([line 647](https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L647)) into `an` and `dbanana`, `lookup()` returns `an` and `banana` respectively with `max_edit_distance_lookup=1`. And the edit distance of `an banana` and `andbanana` is 1 so early exit is triggered without looking at the next split `and` and `banana`

**Comment by bastia1989** [comment]
> We'll use these frequencies for the dictionary `an: 10`, `and: 100`, and `banana: 200`. So the correction distance and count will be `an banana, 1, 10` and `and banana, 1, 100`.
> 
> Without the early exit, `and banana, 1, 100` is returned (by manually commenting it out in the code). The `sort()` works as intended, comparing by edit distance first and preferring higher frequency when a tie occurs ([line 963](https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L963)).
> 
> However, **with** early exit, `an banana, 1, 10` is returned. Since when input string is split ([line 647](https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L647)) into `an` and `dbanana`, `lookup()` returns `an` and `banana` respectively with `max_edit_distance_lookup=1`. And the edit distance of `an banana` and `andbanana` is 1 so early exit is triggered without looking at the next split `and` and `banana`

Got it, thanks.
