### ISSUE TITLE
Short word Transfer Casing suggestions

### ISSUE THREAD

**Issue by d-v-dlee** [mammothb/symspellpy#55]
Just wanted to alert you to some weird behavior with Transfer Casing.

For example:

Fr -> FOr
Nd -> ANd

My symspellpy settings are suggestion_verbosity=TOP, max_edit_distance=2, include_unknown=True and transfer_casing=True. Appreciate your work and the package!

Some example of this are:
ss_py.lookup('Nd', suggestion_verbosity, max_edit_distance=2, include_unknown = True, transfer_casing=True )

**Comment by mammothb** [comment]
I think this is intended behavior https://github.com/mammothb/symspellpy/blob/master/symspellpy/helpers.py#L189 since we only want to transfer/keep the original casing from the input text without caring if it is grammatically correct. We had to make some assumptions on the casing for inserted letters.

You could include some post processing steps after the lookup to ensure that the casing is grammatically correct.
