### ISSUE TITLE
preserve capitalization

### ISSUE THREAD

**Issue by toktammm** [mammothb/symspellpy#62]
Hello symspellpy team,

How should I use the option for preserving capitalization than changing all text to lowercase?

**Comment by mammothb** [comment]
https://symspellpy.readthedocs.io/en/latest/examples/lookup.html#keep-original-casing

https://symspellpy.readthedocs.io/en/latest/examples/lookup_compound.html#keep-original-casing

Capitalization may not work if your misspelling was not capitalized, i.e., isspelling -> misspelling instead of -> Misspelling.
